on:
  schedule:
    - cron:  '0/5 * * * *' # 8am daily. Ref https://crontab.guru/examples.html
jobs:
  wget:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: wget
      working-directory: data/
      run: wget  "https://docs.google.com/spreadsheets/d/e/2PACX-1vSoP79r_KG6CSuIF6Woik3c8o54B_K8EPDYgI_zpPehuYydjNztNzLAPqGwpAoHn6uGLE2_J7zy1Lwa/pub?gid=1484863998&single=true&output=csv" -O ciccio.csv
    - working-directory: data/
      run: |
        mkdir -m 700 ~/.ssh
        echo "${{ secrets.DATA_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 0600 ~/.ssh/id_ed25519
        pushurl="git@github.com:$(git config --local remote.origin.url | sed 's;^https://github\.com/;;')"
        git config remote.origin.pushurl "$pushurl"
        git config --local user.name "githubaction"
        git config --local user.email "githaction@users.noreply.github.com"
        git add ciccio.csv
        git commit -m "ciccio.csv" && git push || :

    
